# Jupyter testing

In [139]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
torch.manual_seed(42)

In [140]:
A = torch.rand(2, 2)
B = torch.rand(2, 2)
print(A, "\n", B)

tensor([[0.8823, 0.9150],
        [0.3829, 0.9593]]) 
 tensor([[0.3904, 0.6009],
        [0.2566, 0.7936]])


In [141]:
class test_architecture(torch.nn.Module):
    def __init__(self):
        super(test_architecture, self).__init__()
        self.l1_conv = nn.Conv1d(1, 3, 3)
        self.l2_conv = nn.Conv1d(3, 3, 3)
        self.l3_conv = nn.Conv1d(3, 3, 3)
        self.l4_lin = nn.Linear(250, 4)
    
    def forward(self, X):

        X = self.l1_conv(X)
        X = self.l2_conv(X)
        X = F.relu(self.l3_conv(X))
        X = self.l4_lin(X)
        return X

model = test_architecture()

In [142]:
input = torch.rand(1, 1, 256)
print(model)
# print(input)
model(input)

test_architecture(
  (l1_conv): Conv1d(1, 3, kernel_size=(3,), stride=(1,))
  (l2_conv): Conv1d(3, 3, kernel_size=(3,), stride=(1,))
  (l3_conv): Conv1d(3, 3, kernel_size=(3,), stride=(1,))
  (l4_lin): Linear(in_features=250, out_features=4, bias=True)
)


tensor([[[-0.7145, -0.2099, -0.0915, -0.1520],
         [-0.3729, -0.1460, -0.0917, -0.1467],
         [-0.5900, -0.1413, -0.1118, -0.1496]]], grad_fn=<ViewBackward0>)

Know we do the training loop.

In [143]:
# for i in range(grids.shape[0]):
#     if i == 0:
#         model = KAN(width=[2,1,1], grid=grids[i], k=k, seed=1, device=device)
#     if i != 0:
#         model = model.refine(grids[i])
#     results = model.fit(dataset, opt="LBFGS", steps=steps)
#     train_losses += results['train_loss']
#     test_losses += results['test_loss']