# Jupyter testing

In [119]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
torch.manual_seed(42)

In [120]:
A = torch.rand(2, 2)
B = torch.rand(2, 2)
print(A, "\n", B)

tensor([[0.8823, 0.9150],
        [0.3829, 0.9593]]) 
 tensor([[0.3904, 0.6009],
        [0.2566, 0.7936]])


In [121]:
class test_architecture(torch.nn.Module):
    def __init__(self):
        super(test_architecture, self).__init__()
        pass
    
    def forward(self, X):

        X = nn.Conv1d(1, 3, 3)(X)
        X = nn.Conv1d(3, 3, 3)(X)
        X = F.relu(nn.Conv1d(3, 3, 3)(X))
        X = nn.Linear(250, 4)(X)
        return X

model = test_architecture()

In [122]:
input = torch.rand(1, 1, 256)
print(model)
# print(input)
model(input)

test_architecture()


tensor([[[ 3.3034e-02, -9.7007e-05,  6.1268e-02, -2.5120e-02],
         [ 4.4811e-02, -6.3267e-02,  1.6868e-02,  3.1803e-02],
         [-8.4215e-03,  5.7282e-03,  8.6392e-03,  7.4329e-02]]],
       grad_fn=<ViewBackward0>)

Know we do the training loop.

In [ ]:
for i in range(grids.shape[0]):
    if i == 0:
        model = KAN(width=[2,1,1], grid=grids[i], k=k, seed=1, device=device)
    if i != 0:
        model = model.refine(grids[i])
    results = model.fit(dataset, opt="LBFGS", steps=steps)
    train_losses += results['train_loss']
    test_losses += results['test_loss']